[project]
name = "state-machine"
version = "0.1.0"
description = "State Machine for AI Agent Workflows"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jsonpath-ng==1.7.0",
    "ply==3.11",
]
